config/routes.rb
Rails.application.routes.draw do
  root controller: :screenshotreqs, action: :index
  resources :screenshotreqs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/screenshot.rb
class Screenshot < ApplicationRecord
  validates :url, presence: true
  validates :image_file_path, presence: true
  validates :image_file_name, presence: true
  # Validate screenshot parameters: URL, image path, image name

  belongs_to :screenshotreq
  # Associate Screenshots to one Screenshotreq

  has_one_attached :image
  # Associate screenshot image stored in Active Storage with Screenshot
end

app/models/screenshotreq.rb
class Screenshotreq < ApplicationRecord
  validates :name, presence: true
  validates :urls, presence: true
  # Validate screenshotreq parameters: name, urls.

  has_many :screenshots, dependent: :destroy
  # Associate and screenshots with screenshotreq / DELETE associated screenshots with screensshotreq DELETE.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/screenshotreqs_controller.rb
# frozen_string_literal: true

class ScreenshotreqsController < ApplicationController
  # This controller governs CRUD functions for Screenshotreq(uest)s and Screenshots

  def index
    # Calls all instances of Screenshotreq model to index page.
    @screenshotreqs = Screenshotreq.all
  end

  def new
    # Required for `create` method.
    @screenshotreq = Screenshotreq.new
  end

  def create
    # CREATE screenshot req instance with validated input parameters.
    @screenshotreq = Screenshotreq.new(screenshotreq_params)

    if @screenshotreq.save
      # If parameters are validated, the URL parameter is parsed...
      parse_urls

      # ... and one screenshot instance is saved per URL.
      create_screenshot_images

      redirect_to root_path
    end
  end

  def show
    # GET saved screenshotreqs.
    @screenshotreq = Screenshotreq.find(params[:id])
  end

  def destroy
    # DELETE saved screenshotreq.
    @screenshotreq = Screenshotreq.find(params[:id])
    @screenshotreq.destroy

    redirect_to root_path

    flash[:notice] = 'Browsershot result has been deleted.'
  end

  private
  # Private methods are not accessible from calls beyond this controller.

  def screenshotreq_params
    # Instantiate screenshotreq parameters.
    params.require(:screenshotreq)
          .permit(:name, :urls)
  end

  def parse_urls
    urls = []
    urls.push(@screenshotreq.urls.gsub(/\s+/, ''))
    # Assign URLs string into an array and remove any whitespace from string.

    urls_split = urls[0].split(';')
    # Mutate single-var URLs string array into an array of multiple URL string vars.

    counter = 1
    urls_split.each do |url|
      image_file_path = "./storage"
      image_file_name = "req#{@screenshotreq.id}shot#{counter}.png"
      @screenshot = Screenshot.create(url: url,
                                      image_file_path: image_file_path,
                                      image_file_name: image_file_name)
      # CREATE one screenshot instance per URL

      @screenshot.screenshotreq = @screenshotreq
      # Associate screenshot instances with screenshotreq instance

      @screenshot.save!
      counter += 1
    end
  end

  def create_screenshot_images
  # Use helper methods provided by ruby_webshot gem to obtain image files.

    @screenshotreq.screenshots.each do |screenshot|
      RubyWebshot.call(screenshot.url,
                       save_file_path: screenshot.image_file_path, 
                       file_name: screenshot.image_file_name, 
                       width: 1366, 
                       height: 768)

      screenshot.image.attach(io: File.open("#{screenshot.image_file_path}/#{screenshot.image_file_name}"),
                              filename: screenshot.image_file_name)
      # Associate captured image file with screenshot instance.
    end

    flash[:notice] = 'Browsershot request has been executed and saved.  Check Storage for results.'
  end

  def error_catch
    # method placeholder
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Browsershot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background">
    </div>
    <div class="background-border">
    </div>
    <div class="copyright">
      Photography and Design <br> &copy; 2020 Max Aubain all rights reserved
    </div>
    <div class="mobile">
      Browsershot is not currently available for mobile and tablet.
    </div>
    <div class="notice">
      <%= notice || alert %>
    </div>
    <div class="navigation">
      <% if !current_page?(root_path)%> 
        <%= link_to 'Home', root_path %> 
      <% else %>
        <%= link_to 'Visit Max', 'https://www.maxaubain.com/about'%>
      <% end %> 
    </div>
    <div class="content">
      <div class="title">
        Browsershot
      </div>
      <div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/screenshotreqs/_submission_form.html.erb
<p>This is the screen shot request submission form.<p>

<%= form_with model: @screenshotreq, local: true do |form| %>

<p>
    <%= form.label :name, 'Name of Requestion' %><br>
    <%= form.text_field :name %>
  </p>
  
  <p>
    <%= form.label :urls, 'URL or URLs (separate multiple URLs with a semicolon ";")' %><br>
    <%= form.text_area :urls %>
  </p>
  
  <p>
    <%= form.submit 'Submit Request'%>
  </p>
<% end %>

app/views/screenshotreqs/index.html.erb
<div class="sub-title">
  Capture and store website screenshots
</div>

<div class="button-container index">
  <div class="button index">
    <%= link_to 'New Request', new_screenshotreq_path, class: "button-text" %>
  </div>

  <div class="dropdown">
    <button class="button-text">
      Storage
    </button>
    <div class="dropdown-content">
      <% @screenshotreqs.each do |screenshotreq| %>
        <%= link_to screenshotreq.name, screenshotreq_path(screenshotreq) %> &nbsp; 
      <% end %>
    </div>
  </div> 
</div>

app/views/screenshotreqs/new.html.erb
<div class="sub-title">
  Define request
</div>

<div class="form-container">
  <div class="form">
    <%= form_with model: @screenshotreq, 
                  url: screenshotreqs_path, 
                  local: true do |form| %>
      <%= form.label :name, 'Username', 
                      class: "sub-sub-title" %>
      <br>
      <%= form.text_field :name,
                          class: "textfield-new",
                          placeholder: "e.g. BrowsershotUser1" %>
      <br><br>
      <%= form.label :urls, 'Websites to screenshot', 
                      class: "sub-sub-title" %>
      <br>
      <%= form.text_area :urls, 
                          class: "textarea-new",
                          placeholder: "e.g. https://www.google.com/; https://www.google.com/maps/" %>
      <br><br>
      <%= form.submit 'Submit', class: "button-text"%>
    <% end %>
  </div>
</div>

app/views/screenshotreqs/show.html.erb
<div class="sub-title">
  Results  
</div>
<div class="request-container">
  <div class="request-tag">
    Request by <%= @screenshotreq.name %>
  </div>
  <div>
    <%= link_to 'Delete', screenshotreq_path(@screenshotreq), method: :delete, class: "button-text"%>
  </div>
</div>

<% @screenshotreq.screenshots.each do |screenshot| %>
  <div>
    <p><%= screenshot.url %></p>
    <%=image_tag screenshot.image, class: "images"%>
  </div>
<% end %>